# Generated by Django 5.2.14 on 2026-05-25 06:57

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0002_appointmentstatushistory_alter_appointment_options_and_more'),
        ('billing', '0001_initial'),
        ('patients', '0002_patientauditlog_patientreport_alter_patient_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='billing',
            options={'ordering': ['-generated_at'], 'verbose_name': 'Billing', 'verbose_name_plural': 'Billings'},
        ),
        migrations.RenameField(
            model_name='billing',
            old_name='insurance_claim',
            new_name='approval_status',
        ),
        migrations.AddField(
            model_name='billing',
            name='claim_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='billing',
            name='claim_status',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='billing',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='billing_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='billing',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='billing',
            name='deleted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='billing_deleted', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='billing',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='billing',
            name='notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='billing',
            name='provider_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='billing',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='billing',
            name='updated_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='billing_updated', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='billing',
            name='appointment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='billings', to='appointments.appointment'),
        ),
        migrations.AlterField(
            model_name='billing',
            name='invoice',
            field=models.CharField(blank=True, max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='billing',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='billings', to='patients.patient'),
        ),
        migrations.AlterField(
            model_name='billing',
            name='payment_method',
            field=models.CharField(choices=[('cash', 'Cash'), ('card', 'Card'), ('upi', 'UPI'), ('insurance', 'Insurance')], max_length=50),
        ),
        migrations.AlterField(
            model_name='billing',
            name='payment_status',
            field=models.CharField(choices=[('generated', 'Generated'), ('processing', 'Processing'), ('paid', 'Paid'), ('overdue', 'Overdue'), ('refunded', 'Refunded'), ('disputed', 'Disputed'), ('pending', 'Pending')], default='generated', max_length=50),
        ),
        migrations.AlterField(
            model_name='billing',
            name='total_amount',
            field=models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddIndex(
            model_name='billing',
            index=models.Index(fields=['invoice'], name='billing_bil_invoice_090b0b_idx'),
        ),
        migrations.AddIndex(
            model_name='billing',
            index=models.Index(fields=['payment_status'], name='billing_bil_payment_061d84_idx'),
        ),
        migrations.AddIndex(
            model_name='billing',
            index=models.Index(fields=['generated_at'], name='billing_bil_generat_0c79b2_idx'),
        ),
        migrations.AddIndex(
            model_name='billing',
            index=models.Index(fields=['is_deleted'], name='billing_bil_is_dele_a90110_idx'),
        ),
        migrations.AddConstraint(
            model_name='billing',
            constraint=models.CheckConstraint(condition=models.Q(('total_amount__gte', 0)), name='billing_total_amount_positive'),
        ),
    ]
