"""
Django settings for hospital_ai project.

Generated by 'django-admin startproject' using Django 5.2.14.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

# =========================================================
# 1. IMPORTS
# =========================================================

import os

from pathlib import Path

from decouple import config

from datetime import timedelta


def csv_env(var_name, default=''):

    raw_value = config(var_name, default=default)

    return [item.strip() for item in raw_value.split(',') if item.strip()]


# =========================================================
# 2. BASE_DIR
# =========================================================

# Build paths inside the project like this: BASE_DIR / 'subdir'.

BASE_DIR = Path(__file__).resolve().parent.parent


# =========================================================
# 3. SECURITY
# =========================================================

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!

SECRET_KEY = config(
    'SECRET_KEY',
    default='django-insecure-secret-key'
)

# SECURITY WARNING: don't run with debug turned on in production!

DEBUG = config(
    'DEBUG',
    default=True,
    cast=bool
)

ALLOWED_HOSTS = csv_env(
    'ALLOWED_HOSTS',
    default='*'
)

INTERNAL_IPS = [
    "127.0.0.1",
]

CORS_ALLOW_ALL_ORIGINS = config(
    'CORS_ALLOW_ALL_ORIGINS',
    default=DEBUG,
    cast=bool,
)

CORS_ALLOWED_ORIGINS = csv_env(
    'CORS_ALLOWED_ORIGINS',
    default='http://localhost:3000,http://127.0.0.1:3000'
)

CSRF_TRUSTED_ORIGINS = csv_env(
    'CSRF_TRUSTED_ORIGINS',
    default='http://127.0.0.1:8000,http://localhost:8000'
)

SECURE_SSL_REDIRECT = config(
    'SECURE_SSL_REDIRECT',
    default=False,
    cast=bool,
)

SESSION_COOKIE_SECURE = config(
    'SESSION_COOKIE_SECURE',
    default=False,
    cast=bool,
)

CSRF_COOKIE_SECURE = config(
    'CSRF_COOKIE_SECURE',
    default=False,
    cast=bool,
)

# Security Headers

SECURE_BROWSER_XSS_FILTER = True

X_FRAME_OPTIONS = 'DENY'


# =========================================================
# 4. INSTALLED APPS
# =========================================================

INSTALLED_APPS = [

    # Django Apps

    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',

    # Third-Party Apps

    'rest_framework',
    'rest_framework_simplejwt.token_blacklist',
    'corsheaders',
    'django_filters',
    'drf_yasg',

    # Custom Apps

    'accounts',
    'patients',
    'doctors',
    'appointments',
    'billing',
    'pharmacy',
    'laboratory',
    'ai_analysis',
    'notifications',
    'dashboard',
]


# =========================================================
# 5. MIDDLEWARE
# =========================================================

MIDDLEWARE = [

    'django.middleware.security.SecurityMiddleware',

    'whitenoise.middleware.WhiteNoiseMiddleware',

    'django.contrib.sessions.middleware.SessionMiddleware',

    'corsheaders.middleware.CorsMiddleware',

    'django.middleware.common.CommonMiddleware',

    'django.middleware.csrf.CsrfViewMiddleware',

    'django.contrib.auth.middleware.AuthenticationMiddleware',

    'django.contrib.messages.middleware.MessageMiddleware',

    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]


# =========================================================
# 6. TEMPLATES
# =========================================================

ROOT_URLCONF = 'hospital_ai.urls'

TEMPLATES = [

    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',

        'DIRS': [BASE_DIR / 'templates'],

        'APP_DIRS': True,

        'OPTIONS': {

            'context_processors': [

                'django.template.context_processors.debug',

                'django.template.context_processors.request',

                'django.contrib.auth.context_processors.auth',

                'django.contrib.messages.context_processors.messages',

                'django.template.context_processors.static',
            ],
        },
    },
]

WSGI_APPLICATION = 'hospital_ai.wsgi.application'


# =========================================================
# 7. DATABASE
# =========================================================

# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases


DB_NAME = config('DB_NAME')

DB_USER = config('DB_USER')

DB_PASSWORD = config('DB_PASSWORD')

DB_HOST = config('DB_HOST')

DB_PORT = config('DB_PORT')

DATABASES = {

    'default': {

        'ENGINE': 'django.db.backends.postgresql',

        'NAME': DB_NAME,

        'USER': DB_USER,

        'PASSWORD': DB_PASSWORD,

        'HOST': DB_HOST,

        'PORT': DB_PORT,
    }
}
     
# =========================================================
# 7.1 REDIS CACHE CONFIGURATION
# =========================================================

CACHES = {

    'default': {

        'BACKEND': 'django.core.cache.backends.redis.RedisCache',

        'LOCATION': config(
            'CACHES_DEFAULT_LOCATION',
            default='redis://127.0.0.1:6379/1'
        ),
    }
}

# =========================================================
# 8. AUTHENTICATION
# =========================================================

AUTH_USER_MODEL = 'accounts.User'

AUTHENTICATION_BACKENDS = [
    'django.contrib.auth.backends.ModelBackend',
]

LOGIN_URL = '/'

LOGIN_REDIRECT_URL = '/dashboard/'

LOGOUT_REDIRECT_URL = '/'

# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [

    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },

    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },

    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },

    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

PASSWORD_HASHERS = [

    'django.contrib.auth.hashers.Argon2PasswordHasher',

    'django.contrib.auth.hashers.PBKDF2PasswordHasher',
]


# =========================================================
# 9. INTERNATIONALIZATION
# =========================================================

# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

# Indian Standard Time

TIME_ZONE = 'Asia/Kolkata'

USE_I18N = True

USE_TZ = True


# =========================================================
# 10. STATIC / MEDIA
# =========================================================

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = 'static/'

STATICFILES_DIRS = [
    BASE_DIR / "static"
]

MEDIA_URL = '/media/'

MEDIA_ROOT = Path(
    config('MEDIA_ROOT', default=str(BASE_DIR / 'media'))
)

STATIC_ROOT = Path(
    config('STATIC_ROOT', default=str(BASE_DIR / 'staticfiles'))
)

STATICFILES_STORAGE = (
    'whitenoise.storage.CompressedManifestStaticFilesStorage'
)

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'


# =========================================================
# 11. REST_FRAMEWORK
# =========================================================

REST_FRAMEWORK = {

    'DEFAULT_AUTHENTICATION_CLASSES': (

        'rest_framework_simplejwt.authentication.JWTAuthentication',
    ),

    'DEFAULT_PERMISSION_CLASSES': (

        'rest_framework.permissions.IsAuthenticated',
    ),

    'DEFAULT_RENDERER_CLASSES': (

        'rest_framework.renderers.JSONRenderer',

        'rest_framework.renderers.BrowsableAPIRenderer',
    ),

    'DEFAULT_FILTER_BACKENDS': [

        'django_filters.rest_framework.DjangoFilterBackend'
    ],

    'DEFAULT_PAGINATION_CLASS':

        'rest_framework.pagination.PageNumberPagination',

    'PAGE_SIZE': 10,

    'DEFAULT_THROTTLE_CLASSES': [

        'rest_framework.throttling.UserRateThrottle',
    ],

    'DEFAULT_THROTTLE_RATES': {

        'user': '100/day'
    }
}


# =========================================================
# 12. SIMPLE_JWT
# =========================================================

SIMPLE_JWT = {

    'ACCESS_TOKEN_LIFETIME': timedelta(
        minutes=config('JWT_ACCESS_TOKEN_LIFETIME', cast=int, default=60)
    ),

    'REFRESH_TOKEN_LIFETIME': timedelta(
        days=config('JWT_REFRESH_TOKEN_LIFETIME', cast=int, default=7)
    ),

    'ROTATE_REFRESH_TOKENS': True,

    'BLACKLIST_AFTER_ROTATION': True,

    'UPDATE_LAST_LOGIN': True,

    'ALGORITHM': 'HS256',

    'SIGNING_KEY': SECRET_KEY,

    'AUTH_HEADER_TYPES': ('Bearer',),

    'AUTH_TOKEN_CLASSES': (

        'rest_framework_simplejwt.tokens.AccessToken',
    ),
}


# =========================================================
# 13. SWAGGER_SETTINGS
# =========================================================

SWAGGER_SETTINGS = {

    'USE_SESSION_AUTH': False,

    'SECURITY_DEFINITIONS': {

        'Bearer': {

            'type': 'apiKey',

            'name': 'Authorization',

            'in': 'header',
        }
    },
}


# =========================================================
# 14. LOGGING
# =========================================================

LOGGING = {

    'version': 1,

    'disable_existing_loggers': False,

    'formatters': {

        'verbose': {

            'format': (
                '{levelname} | {asctime} | '
                '{module} | {message}'
            ),

            'style': '{',
        },

        'simple': {

            'format': '{levelname} | {message}',

            'style': '{',
        },
    },

    'handlers': {

        'file': {

            'level': config('LOG_LEVEL', default='INFO'),

            'class': 'logging.FileHandler',

            'filename': BASE_DIR / 'logs/system.log',

            'formatter': 'verbose',
        },

        'error_file': {

            'level': 'ERROR',

            'class': 'logging.FileHandler',

            'filename': BASE_DIR / 'logs/error.log',

            'formatter': 'verbose',
        },

        'console': {

            'class': 'logging.StreamHandler',

            'formatter': 'simple',
        },
    },

    'loggers': {

        'django': {

            'handlers': [

                'console',
                'file',
                'error_file'
            ],

            'level': config('LOG_LEVEL', default='INFO'),

            'propagate': True,
        },

        'accounts': {

            'handlers': [

                'console',
                'file',
                'error_file'
            ],

            'level': config('LOG_LEVEL', default='INFO'),

            'propagate': True,
        },
    },
}


# =========================================================
# 15. EMAIL CONFIGURATION
# =========================================================

EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'

EMAIL_HOST = config(
    'EMAIL_HOST',
    default='smtp.gmail.com'
)

EMAIL_PORT = config(
    'EMAIL_PORT',
    cast=int,
    default=587
)

EMAIL_USE_TLS = config(
    'EMAIL_USE_TLS',
    cast=bool,
    default=True
)

EMAIL_HOST_USER = config(
    'EMAIL_HOST_USER',
    default=''
)

EMAIL_HOST_PASSWORD = config(
    'EMAIL_HOST_PASSWORD',
    default=''
)

EMAIL_TIMEOUT = config(
    'EMAIL_TIMEOUT',
    cast=int,
    default=30
)

DEFAULT_FROM_EMAIL = config(
    'DEFAULT_FROM_EMAIL',
    default='IHMS Support <support@ihms.com>'
)

# =========================================================
# 16. CELERY CONFIGURATION
# ========================================================= 

CELERY_BROKER_URL = config(
    'CELERY_BROKER_URL',
    default='redis://127.0.0.1:6379/0'
)

CELERY_RESULT_BACKEND = config(
    'CELERY_RESULT_BACKEND',
    default=CELERY_BROKER_URL
)

CELERY_ACCEPT_CONTENT = ['json']

CELERY_TASK_SERIALIZER = 'json'

CELERY_RESULT_SERIALIZER = 'json'

# =========================================================
# 17. AI / OCR CONFIGURATION
# =========================================================

MODEL_PATH = config(
    'MODEL_PATH',
    default=str(BASE_DIR / 'ml_models')
)

VOICE_MODEL_PATH = config(
    'VOICE_MODEL_PATH',
    default=str(BASE_DIR / 'ml_models' / 'voice_analysis' / 'voice_model.pkl')
)

DISEASE_MODEL_PATH = config(
    'DISEASE_MODEL_PATH',
    default=str(BASE_DIR / 'ml_models' / 'disease_prediction' / 'disease_model.pkl')
)

TESSERACT_CMD = config(
    'TESSERACT_CMD',
    default='/usr/bin/tesseract'
)
