# Generated by Django 5.2.14 on 2026-05-18 12:09

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('patients', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AIAnalysis',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('voice_stress_score', models.FloatField()),
                ('disease_prediction', models.CharField(max_length=255)),
                ('mental_health_result', models.CharField(max_length=255)),
                ('confidence_score', models.FloatField()),
                ('audio_file', models.FileField(upload_to='voice_analysis/')),
                ('analysis_report', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='patients.patient')),
            ],
        ),
    ]
